### PR TITLE
Add TypeID community implementation for Erlang

### PR DESCRIPTION
**Pull request by eproxus**
## Summary

Adds keysmith, a new TypeID Erlang community implementation.

## How was it tested?

Markdown has been manually reviewed.

### CODE REVIEW

**Comment by loreto** [comment]
@eproxus Thanks for submitting!

Could you point me to the tests validating conformance with the typeid spec? Basically the tests that tests these cases:
- https://github.com/jetify-com/opensource/blob/main/typeid/typeid/spec/invalid.yml
- https://github.com/jetify-com/opensource/blob/main/typeid/typeid/spec/valid.yml

**Comment by eproxus** [comment]
@loreto 👍 I'm working on adding those. I'll let you know when it is done.

**Comment by eproxus** [comment]
@loreto Looking into the test data, it seems the test data does not follow the specification. The specification says:

> 3. A UUID suffix: a 128-bit UUIDv7 encoded as a 26-character string in base32.

But the test data contains (among others) the UUID `00000000-0000-0000-0000-000000000000` which **is not** a valid UUID version 7 (the valid version with all zeroes would be `00000000-0000-7000-8000-000000000000`).

Since my implementation does strict parsing and generation of UUIDs it cannot use this test data for automated tests.

**Comment by eproxus** [comment]
I realize now that any custom UUID is technically allowed by the spec. I've added [validation for the invalid IDs for now](https://github.com/eproxus/keysmith/blob/main/test/keysmith_tests.erl#L169-L179), and will work on adding support for validating the valid IDs as well.

**Comment by loreto** [comment]
> I realize now that any custom UUID is technically allowed by the spec. I've added [validation for the invalid IDs for now](https://github.com/eproxus/keysmith/blob/main/test/keysmith_tests.erl#L169-L179), and will work on adding support for validating the valid IDs as well.

Thanks! Yeah the way I see it is:
- By default a library should always generate new TypeIDs using UUIDv7
- However, if the user of the library so chooses, they can encode any UUID as a TypeID

**Comment by eproxus** [comment]
I've now added support for a more general UUID format so both the valid and invalid test files now pass. You can find the test code here: https://github.com/eproxus/keysmith/blob/main/test/keysmith_tests.erl#L347-L383

**Comment by loreto** [comment]
LGTM

**Review by LucilleH — APPROVED** [review]

**Comment by eproxus** [comment]
@loreto Thanks! 🙏

**Pull request merged**
